# Generated by Django 6.0 on 2026-08-20 18:48

import account.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fullname', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن')),
                ('role', models.CharField(choices=[('superuser', 'سوپریوزر'), ('owner', 'مالک')], default='owner', max_length=20, verbose_name='نقش')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='user/default/user3.png', null=True, upload_to=functools.partial(account.models.upload_file, upload_dir='user/upload/'), verbose_name='تصویر پروفایل')),
                ('otp', models.PositiveIntegerField(blank=True, null=True, verbose_name='کد یکبار مصرف')),
                ('otp_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال کد یکبار مصرف')),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='account_myu_created_f66927_idx'), models.Index(fields=['phone'], name='account_myu_phone_faa154_idx')],
            },
        ),
    ]
