# Generated by Django 6.0 on 2026-08-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_phone', models.CharField(max_length=11, verbose_name='گیرنده')),
                ('body', models.TextField(verbose_name='متن')),
                ('event', models.CharField(blank=True, max_length=40, verbose_name='رویداد')),
                ('status', models.CharField(choices=[('sent', 'ارسال شد'), ('failed', 'ناموفق'), ('dev', 'حالت توسعه')], default='dev', max_length=10, verbose_name='وضعیت')),
                ('error', models.CharField(blank=True, max_length=300, verbose_name='خطا')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'پیامک',
                'verbose_name_plural': 'پیامک\u200cها',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='account_sms_created_790a05_idx')],
            },
        ),
    ]
