# Generated by Django 6.0 on 2026-08-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_myuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='business_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='نام کسب\u200cوکار'),
        ),
    ]
