# Generated by Django 6.0 on 2026-08-26 19:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='گفتگوی جدید', max_length=80, verbose_name='عنوان')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین فعالیت')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'کاربر'), ('assistant', 'دستیار')], max_length=10, verbose_name='نقش')),
                ('body', models.TextField(verbose_name='متن')),
                ('tools_used', models.JSONField(blank=True, default=list, verbose_name='ابزارهای استفاده\u200cشده')),
                ('suggestion', models.JSONField(blank=True, null=True, verbose_name='پیشنهاد عمل')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='گفتگو')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['owner', '-updated'], name='chat_conver_owner_i_7d2ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created'], name='chat_messag_convers_d116fc_idx'),
        ),
    ]
