# Generated by Django 6.0 on 2026-09-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='widgets',
            field=models.JSONField(blank=True, default=list, verbose_name='ویجت\u200cها'),
        ),
    ]
