# Generated by Django 6.0 on 2026-09-22 00:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_widgets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('code', models.TextField(verbose_name='برنامهٔ رابط')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pins', to='chat.message', verbose_name='پیام')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_views', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'Pinned view',
                'verbose_name_plural': 'Pinned views',
                'ordering': ['-created', '-id'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'message'), name='chat_pin_once_per_message')],
            },
        ),
    ]
