"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# مقادیر حساس از فایل .env خوانده می‌شوند (کنار manage.py). این فایل نباید در
# گیت باشد؛ نمونهٔ آن در .env.example قرار دارد. روی سرور واقعی می‌توان به‌جای
# فایل، متغیرهای محیطی سیستمی را ست کرد — decouple هر دو را می‌خواند.

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="", cast=Csv())


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "account.apps.AccountConfig",
    "home.apps.HomeConfig",
    "chat.apps.ChatConfig",
    "api.apps.ApiConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

# به‌جای یوزر دیفالت جنگو از این یوزر استفاده کن
AUTH_USER_MODEL = "account.MyUser"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                'django.template.context_processors.debug',
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {  # تغییر دیتابیس از دیفالت به پستگر اس کیو ال
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME", default="CRM"),
        "USER": config("DB_USER", default="postgres"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="localhost"),
        # روی این ماشین دو نسخهٔ پستگرس نصب است: ۵۴۳۲ نسخهٔ ۱۷ و ۵۴۳۳ نسخهٔ ۱۸.
        # دیتابیس CRM روی ۵۴۳۳ است؛ اگر پورت را جا بیندازید به نسخهٔ ۱۷ وصل
        # می‌شوید و خطای «database "CRM" does not exist» می‌گیرید.
        "PORT": config("DB_PORT", default="5433"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC"

TIME_ZONE = 'Asia/Tehran'  # برای ایران

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# اینجا فایل های استاتیک رو به جنگو معرفی میکنیم
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Django REST Framework
# احراز هویت مبتنی بر سشن خود جنگو + CSRF؛ پیش‌فرض همه‌چیز نیازمند لاگین است
REST_FRAMEWORK = {
    # مشخص میکنه از چه روش هایی برای احراز هویت استفاده بشه
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    # مجوزهای دسترسی
    # پیش‌فرض: هر endpoint نیازمند لاگین است. endpointهای عمومی خودشان
    # permission_classes = [AllowAny] ست می‌کنند.
    # نکته: DjangoModelPermissionsOrAnonReadOnly برای ویوهای مدل‌محور (با queryset)
    # است و روی APIViewهای ساده AssertionError می‌دهد؛ برای این پروژه مناسب نیست.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # فرآیند رندر کردن
    'DEFAULT_RENDERER_CLASSES': [
        # اگه آدرس ای پی آی مورد نظر داخل مرورگر زده بشه، اطلاعات به صورت جیسون نمایش داده میشه
        'rest_framework.renderers.JSONRenderer',
        # اگه آدرس ای پی آی مورد نظر داخل مرورگر زده بشه، اطلاعات به صورت جیسون و مفصل (با پیجینیشن) نمایش داده میشه
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    # فرآیند پارس کردن دیتا، (تبدیل دیتای ورودی (جیسون) به دیتای ساده مانند لیست، دیکشنری و ...)
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    # مدیریت صفحه بندی برای api ها
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    # محدودسازی نرخ (ضد brute-force) فقط روی ویوهای دارای throttle_scope
    "DEFAULT_THROTTLE_CLASSES": ["rest_framework.throttling.ScopedRateThrottle"],
    "DEFAULT_THROTTLE_RATES": {"login": "10/min", "otp": "5/min"},
}

# امنیت سشن و CSRF (مدل جدا با Same-Origin Proxy در Vite)
# کوکی سشن فقط از طریق HTTP خوانده می‌شود تا در برابر XSS مصون باشد
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

# توکن CSRF باید برای جاوااسکریپت قابل خواندن باشد تا در هدر X-CSRFToken ارسال شود
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "Lax"

# امنیت CSRF: مشخص می‌کند درخواست‌های تغییردهنده (POST/PUT/DELETE) از کدام Origin
# «خودی» محسوب می‌شوند. خودِ حفاظت CSRF کامل برقرار است (هم توکن و هم Origin بررسی
# می‌شوند)؛ این لیست فقط مبدأهای مجاز را تعیین می‌کند.
if DEBUG:
    # در توسعه، فرانت (Vite) روی پورت جداست. Vite معمولاً 5173 است اما اگر اشغال باشد
    # پورت بعدی را می‌گیرد؛ پس کل محدودهٔ متداول را مجاز می‌کنیم تا فلوها مستقل از پورتِ
    # دقیق کار کنند و پایه به یک پورت ثابت گره نخورد.
    CSRF_TRUSTED_ORIGINS = [
        f"http://{host}:{port}"
        for host in ("localhost", "127.0.0.1")
        for port in range(5173, 5184)  # 5173 تا 5183
    ]
else:
    # در پروداکشن، فرانت و بک‌اند Same-Origin پشت یک reverse proxy سرو می‌شوند.
    # دامنه(های) واقعی را از متغیر محیطی بخوان (با کاما جدا شده)، مثلاً:
    #   CSRF_TRUSTED_ORIGINS="https://crm.example.com,https://www.crm.example.com"
    CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="", cast=Csv())
    # کوکی‌ها فقط روی HTTPS ارسال شوند
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# حداکثر حجم فایل برای آپلود: 2.5 مگابایت
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440

# تنظیمات مربوط به پوشه media
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# پیامک (کاوه‌نگار)
# SMS_DEV_MODE=True یعنی پیامک واقعاً ارسال نمی‌شود و فقط در SMSLog ثبت می‌گردد.
# لازم است چون کاوه‌نگار فقط به شماره‌های تاییدشدهٔ صاحب حساب ارسال دارد و
# شماره‌های تست همیشه ۵۰۲ می‌گیرند، یعنی فلوی تایید کد اصلاً قابل آزمایش نمی‌شد.
# برای پروداکشن باید False شود، وگرنه کاربران هیچ پیامکی دریافت نمی‌کنند.
SMS_DEV_MODE = config("SMS_DEV_MODE", default=True, cast=bool)

# اگر پر باشد، هر پیامکی که باید ارسال شود به **همین شماره** می‌رود، ولی متنش با
# دادهٔ واقعیِ گیرندهٔ اصلی ساخته می‌شود و شمارهٔ اصلی هم در SMSLog ثبت می‌ماند.
# لازم است چون کاوه‌نگار فقط به شماره‌های تاییدشدهٔ صاحب حساب ارسال دارد و
# شماره‌های دفترِ آزمایشی همه ساختگی‌اند.
SMS_TEST_RECIPIENT = config("SMS_TEST_RECIPIENT", default="")

# نامِ الگوهای کاوه‌نگار. اینها پیکربندیِ استقرارند نه ثابتِ کد: اگر روزی الگویی
# در پنل با نامِ دیگری ساخته شود، نباید کد عوض شود.
SMS_TEMPLATE_OTP = config("SMS_TEMPLATE_OTP", default="crm")
SMS_TEMPLATE_FORGET_PASSWORD = config("SMS_TEMPLATE_FORGET_PASSWORD", default="crm-forget-pass")
SMS_TEMPLATE_DEBT_REMINDER = config("SMS_TEMPLATE_DEBT_REMINDER", default="crm-debt-reminder")
KAVENEGAR_API_KEY = config("KAVENEGAR_API_KEY", default="")
# این خط حقوقیه و خدماتی نشده. برای خدماتی شدن باید حقوقی بود مثلا باید شرکت ثبت شده داشت
# بنابراین با این حال از این خط فقط برای پیام های تبلیغاتی (مسیج بدون توکن) میشه استفاده کرد
KAVENEGAR_SENDER = config("KAVENEGAR_SENDER", default="1000009999090")
