# Generated by Django 6.0 on 2026-08-20 19:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=80, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('code', models.IntegerField(choices=[(-1, 'بدهکار'), (0, 'بی حساب'), (1, 'بستانکار')], default=0, verbose_name='وضعیت حساب')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_customerOwners', to='home.customer', verbose_name='مشتری')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_customerOwners', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='owners',
            field=models.ManyToManyField(related_name='owner_customers', through='home.CustomerOwner', to=settings.AUTH_USER_MODEL, verbose_name='مالکان'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt', models.IntegerField(default=0, verbose_name='مبلغ نسیه (تومان)')),
                ('paid', models.IntegerField(default=0, verbose_name='مبلغ پرداختی (تومان)')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ تراکنش')),
                ('year', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='سال شمسی')),
                ('month', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='ماه شمسی')),
                ('day', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='روز شمسی')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_transactions', to='home.customer', verbose_name='مشتری')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_transactions', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='customerowner',
            index=models.Index(fields=['-created'], name='home_custom_created_6da701_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerowner',
            unique_together={('customer', 'owner')},
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['-created'], name='home_custom_created_d0ab95_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['code'], name='home_custom_code_58bdf8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-created'], name='home_transa_created_387b44_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['year', 'month', 'day'], name='home_transa_year_9a148d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner', 'customer', '-created'], name='home_transa_owner_i_093293_idx'),
        ),
    ]
